fix validate-appdata test
ranfdev/Geopard pull request #101
Opened 2024-04-04 06:52 UTC by iFoundSilentHouse

closes https://github.com/ranfdev/Geopard/issues/100

2024-04-05 20:40 UTC, tfuxu requested changes
I think you should instead put the list inside a paragraph, so that formatting doesn't look weird when rendered

2024-04-06 02:10 UTC, iFoundSilentHouse commented
Like this?
```
diff --git a/data/com.ranfdev.Geopard.metainfo.xml.in.in b/data/com.ranfdev.Geopard.metainfo.xml.in.in
index d2ffa1f..e27ffb2 100644
--- a/data/com.ranfdev.Geopard.metainfo.xml.in.in
+++ b/data/com.ranfdev.Geopard.metainfo.xml.in.in
@@ -88,10 +88,12 @@
     </release>
     <release version="1.1.0" date="2022-05-19">
       <description>
-        <p>Improved design, with completely new pages for downloads, input requests, external links, errors</p>
-        <p>Added more spacing between links to make them easier to click on small screens</p>
-        <p>Added zoom functionality, via shortcuts or directly from the popover menu</p>
-        <p>Streaming button (alpha) for some audio/video file types</p>
+        <p>
+          <li>Improved design, with completely new pages for downloads, input requests, external links, errors</li>
+          <li>Added more spacing between links to make them easier to click on small screens</li>
+          <li>Added zoom functionality, via shortcuts or directly from the popover menu</li>
+          <li>Streaming button (alpha) for some audio/video file types</li>
+        </p>
       </description>
     </release>
     <release version="1.0.1" date="2022-05-07">
'''

2024-04-06 02:21 UTC, iFoundSilentHouse commented
Test failed that way with ```<p> is too short```

2024-04-06 02:42 UTC, iFoundSilentHouse commented
```
diff --git a/data/com.ranfdev.Geopard.metainfo.xml.in.in b/data/com.ranfdev.Geopard.metainfo.xml.in.in
index f35c019..8f58603 100644
--- a/data/com.ranfdev.Geopard.metainfo.xml.in.in
+++ b/data/com.ranfdev.Geopard.metainfo.xml.in.in
@@ -88,12 +88,10 @@
     </release>
     <release version="1.1.0" date="2022-05-19">
       <description>
-        <ul>
-          <li>Improved design, with completely new pages for downloads, input requests, external links, errors</li>
-          <li>Added more spacing between links to make them easier to click on small screens</li>
-          <li>Added zoom functionality, via shortcuts or directly from the popover menu</li>
-          <li>Streaming button (alpha) for some audio/video file types</li>
-        </ul>
+        <p><li>Improved design, with completely new pages for downloads, input requests, external links, errors</li></p>
+        <p><li>Added more spacing between links to make them easier to click on small screens</li></p>
+        <p><li>Added zoom functionality, via shortcuts or directly from the popover menu</li></p>
+        <p><li>Streaming button (alpha) for some audio/video file types</li></p>
       </description>
     </release>
     <release version="1.0.1" date="2022-05-07">
```
Failed with same error

2024-04-06 17:19 UTC, iFoundSilentHouse commented
```
-        <ul>
-          <li>Improved design, with completely new pages for downloads, input requests, external links, errors</li>
-          <li>Added more spacing between links to make them easier to click on small screens</li>
-          <li>Added zoom functionality, via shortcuts or directly from the popover menu</li>
-          <li>Streaming button (alpha) for some audio/video file types</li>
-        </ul>
+        <p>
+          <ul>
+            <li>Improved design, with completely new pages for downloads, input requests, external links, errors</li>
+            <li>Added more spacing between links to make them easier to click on small screens</li>
+            <li>Added zoom functionality, via shortcuts or directly from the popover menu</li>
+            <li>Streaming button (alpha) for some audio/video file types</li>
+          </ul>
+        </p>
```
Failed with same error

2024-04-07 16:27 UTC, tfuxu commented
I'm not sure how the packaging works in void, but can you use `validate-relax` in appstream-util?

2024-04-07 16:58 UTC, iFoundSilentHouse commented
It worked! Thank you. Should I use it as main patch for void package?

2024-04-09 17:19 UTC, ranfdev approved these changes

2024-04-09 17:19 UTC, merged

2024-04-09 17:19 UTC, ranfdev commented
thanks everyone